import { ArrayElementOf } from "./ArrayElementOf.js";

export type ContentTextKey = ArrayElementOf<typeof contentTextKeys>;
export const contentTextKeys = [
    'languageCode',
    'buttonHome',
    'buttonAbout',
    'footerText1',
    'footerText2',
    'homeWelcomeMessage',
    'homeHeader1',
    'homeText1',
    'homeHeader2',
    'homeText2',
    'homeText3',
    'homeProceedButton',
    'screeningHeader',
    'screeningHeader2',
    'errorMessage',
    'screeningDate',
    'screeningDateMarried',
    'modalText1',
    'modalText2',
    'modalText3',
    'modalText4',
    'modalExitButton',
    'screeningProceedButton',
    'stepsHeader',
    'stepsHeader2',
    'stepsHeader3',
    'stepsProceedButton',
    'step1Header',
    'step1Title',
    'step1Instructions',
    'step1VideoID',
    'step1Tip1',
    'step1Tip2',
    'step1Ending',
    'step1ProceedButton',
    'step2Header',
    'step2Title',
    'step2Instructions',
    'step2Tip1',
    'step2Tip2',
    'step2Header2',
    'step2Tip4',
    'step2Tip5',
    'step2Tip6',
    'step2ProceedButton1',
    'step2ProceedButton2',
    'step2ProceedButton3',
    'step2Ending',
    'step2ProceedButton4',
    'step3Header',
    'step3Title',
    'step3Instructions',
    'step3Header2',
    'step3Text2',
    'step3Header3',
    'step3Text3',
    'step3Tip1',
    'step3Tip2',
    'step3Tip3',
    'step3Text4',
    'step3Text5',
    'step3Text6',
    'progressBarHeader',
    'errorMessageEmail',
    'errorMessagePhone',
    'errorMessageZip',
    'required',
    'optional',
    'closedMessage',
    'closingDate',
] as const;
export type ContentText = Record<ContentTextKey, string>;

export function isContentTextKey(value: unknown | undefined | null): value is ContentTextKey {
    if (value == null) return false;
    else if (typeof value !== 'string') return false;
    return contentTextKeys.includes(value as ContentTextKey);
}