env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  # - "react-app"
  - plugin:react-hooks/recommended
parserOptions:
  sourceType: module
plugins: 
  - react
  - "prettier"
rules: 
  "prettier/prettier": 1
