---
version: "3.9"

services:
  app:
    image: e-immigrate
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    env_file: ./backend/.secrets/.env
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://eimmigrate:eimmigrate@mongo/eimmigrate?authSource=admin
      # - SENDGRID_API_KEY=SG.hxxxx
    labels:
      - "org.opensourcesanjose.app=eimmigrate"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:8080"
    labels:
      - "org.opensourcesanjose.app=eimmigrate"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: eimmigrate
      MONGO_INITDB_ROOT_PASSWORD: eimmigrate
      MONGO_INITDB_DATABASE: eimmigrate
  
  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./docker/reverse-proxy/conf_d:/etc/nginx/conf.d
      - ./docker/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8096:80
    restart: unless-stopped

volumes:
  mongo-data:
    labels:
      org.opensourcesanjose.app: eimmigrate