FROM node:18.15.0-buster-slim as builder

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app
RUN npm run build

FROM openresty/openresty
COPY ./AWS-Deployment/client/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./AWS-Deployment/client/nginx/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY --from=builder /usr/src/app/build /usr/local/openresty/nginx/html
EXPOSE 80