global:
  image:
    repository: 253016134262.dkr.ecr.us-west-2.amazonaws.com/eimmigrate
    tag: ""
  deployed_url: eimmigrate.opensourcesanjose.org
  eks_shared_environment: prod
  doppler_secret_ref: eimmigrate-prod-doppler-secrets

web:
  replicaCount: 1
  command: [ "node", "./backend/index.js" ]
  cpu:
    requests: 250m
    limit: 2000m
  memory:
    requests: 256Mi
    limit: 2048Mi
  port: 3001

serviceaccount:
  create: false

vpa:
  create: false
