---
name: ci
run-name: ci ${{ github.event_name}} ${{ github.ref_name }} by ${{ github.actor }}
on:
  schedule:
    - cron: '20 11 * * *'
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: gha
          aws-region: us-west-1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.push.head_commit.id }}
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: make build
